### ISSUE TITLE
Planes enter tokyo drift mode when they land

### ISSUE THREAD

**Issue by shaneshort** [plane-watch/pw-pipeline#124]
Planes appear to get incorrect headings when they change from airborne position to ground position:

![image](https://user-images.githubusercontent.com/286620/210938204-021eee97-c90c-4eb8-91cf-fc62860e80d2.png)

**Comment by tardoe** [comment]
Fixed under https://github.com/plane-watch/pw-pipeline/commit/3ce3162a824f7d0c50739bd6daf9831501b1914e
