### ISSUE TITLE
SBS-1 Not Working?

### ISSUE THREAD

**Issue by mikenye** [plane-watch/pw-pipeline#227]
When starting pw_ingest with this command line:

```
/usr/local/bin/pw_ingest --tag mlat-mux-wa --fetch sbs1://127.0.0.1:30003 --sink nats://nats-ingest.plane.watch:4222 simple
```

pw_ingest fails to start, with the following log:

```
Fri Nov 24 14:14:32 UTC 2023 ERR Do not have a reference lat/lon - will not decode surface position frames ref-lat=0 ref-lon=0
Fri Nov 24 14:14:32 UTC 2023 INF Monitoring listener Listener Port=9602
Fri Nov 24 14:14:32 UTC 2023 INF Including Ingest Tap
Fri Nov 24 14:14:32 UTC 2023 INF Just added a producer Section=Tracker num workers=5 source=127.0.0.1:30003
Fri Nov 24 14:14:32 UTC 2023 INF Fetching From Host: 127.0.0.1:30003 Name=127.0.0.1:30003 ProducerType=SBS1 section=127.0.0.1:30003
Fri Nov 24 14:15:03 UTC 2023 ERR error="Failed to Parse Input - not enough parameters: " Section=Tracker Tag=mlat-mux-wa
```

**Comment by mikenye** [comment]
[sbs.out.txt](https://github.com/plane-watch/pw-pipeline/files/13512236/sbs.out.txt)

@bluntelk `mlat-server` sends a linefeed (hex `0a`) every 30 seconds. A hex dump from nc is attached. This is likely a simple fix - ignore `0x0a` :)

**Comment by mikenye** [comment]
[mlat-results.sbs.out.txt](https://github.com/plane-watch/pw-pipeline/files/13512520/mlat-results.sbs.out.txt)

Hexdump of `mlat-server` output with some results.

**Comment by bluntelk** [comment]
I have pushed a fix for this - let's test it out!
